# Generated by Django 3.2 on 2021-04-08 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_heat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='csv',
            field=models.FileField(default=django.utils.timezone.now, upload_to='fichier'),
            preserve_default=False,
        ),
    ]
