# Generated by Django 3.2 on 2021-04-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_heat', '0002_fichier_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='csv',
            field=models.FileField(upload_to='fichiers'),
        ),
    ]
